### ISSUE TITLE
Link dirrection wrong?

### ISSUE THREAD

**Issue by Norwayman** [Jimmi08/links_page#1]
I know that the plugin is in progress, but I discovered this:
The site link goes to this: http://localhost/e107/links_page/links
and should go to this: http://localhost/e107/e107_plugins/links_page/links.php   

Am I right?
As you know I am not a programmer, but at least
http://localhost/e107/e107_plugins/links_page/links.php  works for me to get further.

I am working locally on my WampServer :)

**Comment by Jimmi08** [comment]
Hi,
thank you. New plugins should have SEF-URL functionality. This is because this line in e_url.php:

![image](https://cloud.githubusercontent.com/assets/5429548/12346481/ea0014c8-bb54-11e5-8a0f-6b2738e5e063.png)

The line "redirect" is actual path that is loaded.  Look at Forum, it works the same way. But if you look at Gallery or Download plugin, it's different. They don't use e_url.php, but they have folder "url" - it's too much for me now to understand how it works. I suppose it's related to possibility of setting SEF urls path in Admin Preferencies. There are no documentation about this. With regex it's just about trying and see if it works.

**Comment by Norwayman** [comment]
Thank you for pointing that out. The SEF was disabled in the plugin. Once enabled to index it works like a charm! :) Thanks

**Comment by Jimmi08** [comment]
You are welcome. What do you mean? What did you enabled? Try latest update, I hope all urls are working (there was problem with 1.0.4 too, now should be working all settings).

**Comment by Norwayman** [comment]
The URL link did not automatically appear when I edited the site link. But
I saw that SEF for this dite link was disabled. When I abled it to Idex the
URL automatically appeared in that field. Then trying out the link on my
front page it worked perfect. If you need screenshots I can send you later.
I am on my mobile now.
15. jan. 2016 12:02 skrev "Jimako" <notifications@github.com>:

**Comment by Jimmi08** [comment]
Oh, I know what you mean, I noticed this with other plugins too. I needed resave sitelinks. When I update to latest e107 github, I will try to test it. Thank you
